# requirements:
# auth_server/db_password.secret - contains the password for the auth_server_db

services:
  auth_server_db:
    image: mongo:5.0
    container_name: auth_server_db
    ports:
      - 8043:27017
    volumes:
      - auth-server-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/auth_server_db_password
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    secrets:
      - auth_server_db_password

  auth_server_sessions_store:
    image: redis:7
    container_name: auth_server_sessions_store
    ports:
      - 8044:6379
    volumes:
      - auth-server-redis-data:/data

  client_sessions_store:
    image: redis:7
    container_name: client_sessions_store
    ports:
      - 8045:6379
    volumes:
      - client-redis-data:/data

  resource_server_db:
    image: mongo:5.0
    container_name: resource_server_db
    ports:
      - 8046:27017
    volumes:
      - resource-server-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/resource_server_db_password
    secrets:
      - resource_server_db_password

  initialization_done:
    image: alpine:latest
    depends_on:
      auth_server_db:
        condition: service_healthy

secrets:
  auth_server_db_password:
    file: auth_server/db_password.secret
  resource_server_db_password:
    file: resource_server/db_password.secret

volumes:
  auth-server-mongo-data:
    external: true
  auth-server-redis-data:
    external: true
  client-redis-data:
    external: true
  resource-server-mongo-data:
    external: true
