# requirements:
# auth_server/db_password.secret - contains the password for the auth_server_db

services:
  auth_server_db:
    image: mongo:5.0
    container_name: auth_server_db
    ports:
      - 8043:27017
    volumes:
      - auth-server-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

  auth_server_sessions_store:
    image: redis:7
    container_name: auth_server_sessions_store
    ports:
      - 8044:6379
    volumes:
      - auth-server-redis-data:/data

  client_sessions_store:
    image: redis:7
    container_name: client_sessions_store
    ports:
      - 8045:6379
    volumes:
      - client-redis-data:/data

secrets:
  db_password:
    file: auth_server/db_password.secret

volumes:
  auth-server-mongo-data:
    external: true
  auth-server-redis-data:
    external: true
  client-redis-data:
    external: true
